name: CI Checks

on: [push, pull_request]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        uses: ./.github/actions/setup-env

      - name: Install pylint
        run: pip install pylint

      - name: Run Linter (pylint)
        run: pylint --rcfile=.pylintrc .

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        uses: ./.github/actions/setup-env

      - name: Install mypy
        run: pip install mypy

      - name: Run Type Checker (mypy)
        run: mypy --ignore-missing-imports .
